apiVersion: v1
kind: Service
metadata:
  name: reviewiq
  namespace: reviewiq
  labels:
    app: reviewiq
spec:
  selector:
    app: reviewiq
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: reviewiq
  namespace: reviewiq
  labels:
    app: reviewiq
spec:
  to:
    kind: Service
    name: reviewiq
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
